/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package VistaController;

/**
 *
 * @author Cakri
 */
public class ReportesView extends javax.swing.JInternalFrame {

    /**
     * Creates new form Reportes
     */
    public ReportesView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        cbMasVendidos = new javax.swing.JCheckBox();
        cbMenosVendidos = new javax.swing.JCheckBox();
        cbMenorPrecio = new javax.swing.JCheckBox();
        cbMayorPrecio = new javax.swing.JCheckBox();
        cbInvenMinimo = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblInventario = new javax.swing.JTable();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton1 = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Inventario");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Estado del inventario");

        cbMasVendidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMasVendidos.setText("Productos mas vendidos");

        cbMenosVendidos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMenosVendidos.setText("Productos menos vendidos");

        cbMenorPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMenorPrecio.setText("Menor precio");
        cbMenorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMenorPrecioActionPerformed(evt);
            }
        });

        cbMayorPrecio.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbMayorPrecio.setText("Mayor precio");
        cbMayorPrecio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbMayorPrecioActionPerformed(evt);
            }
        });

        cbInvenMinimo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        cbInvenMinimo.setText("Inventario minimo");
        cbInvenMinimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbInvenMinimoActionPerformed(evt);
            }
        });

        tblInventario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Precio", "Stock", "Categoria", "Descripcion", "Proveedor"
            }
        ));
        jScrollPane1.setViewportView(tblInventario);

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jToggleButton1.setText("Limpiar");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("Buscar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMasVendidos)
                                    .addComponent(cbMenosVendidos))
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cbMenorPrecio)
                                    .addComponent(cbMayorPrecio))
                                .addGap(30, 30, 30)
                                .addComponent(cbInvenMinimo))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(38, 38, 38)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMasVendidos)
                    .addComponent(cbMenorPrecio)
                    .addComponent(cbInvenMinimo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbMenosVendidos)
                    .addComponent(cbMayorPrecio))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 338, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jToggleButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 53, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbMayorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMayorPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMayorPrecioActionPerformed

    private void cbMenorPrecioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbMenorPrecioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbMenorPrecioActionPerformed

    private void cbInvenMinimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbInvenMinimoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbInvenMinimoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox cbInvenMinimo;
    private javax.swing.JCheckBox cbMasVendidos;
    private javax.swing.JCheckBox cbMayorPrecio;
    private javax.swing.JCheckBox cbMenorPrecio;
    private javax.swing.JCheckBox cbMenosVendidos;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JTable tblInventario;
    // End of variables declaration//GEN-END:variables
}
